# config.yaml
# Simple configuration for Service Aggregator
database:
  path: "services.db"
  backup_interval_hours: 24

extraction:
  max_concurrent: 3
  delay_between_requests: 2
  timeout_seconds: 30

google_sheets:
  credentials_file: "credentials.json"
  default_sheet_name: "Service Plans Data"

admin_interface:
  port: 8501
  auto_refresh_minutes: 60

# Known providers for auto-extraction
providers:
  mobile:
    - "https://www.telia.no/mobilabonnement"
    - "https://www.telenor.no/mobilabonnement/"
    - "https://www.ice.no/mobilabonnement/"
  electricity:
    - "https://www.fortum.com/no/strom/stromavtale"
    - "https://www.forbrukerradet.no/strompris/"
  internet:
    - "https://www.telenor.no/privat/internett/"
    - "https://www.telia.no/internett/"